services:
  app:
    build: 
      context: .
      dockerfile: app-prod.DOCKERFILE
    ports:
      - "80:3000"

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db:/data/db
      - ./data:/data-init:ro
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - ./scripts/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@db:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  db:
